FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc g++ libgl1 libglib2.0-0 libhdf5-dev git curl wget unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir numpy

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit -r requirements.txt

COPY . .

RUN mkdir -p /app/outputs /workspace/dynunet_weights

ENV DYNUNET_WEIGHTS_DIR=/workspace/dynunet_weights
ENV DYNUNET_WEIGHTS_FILE=model_brats_mri_segmentation.pt
ENV MPLBACKEND=Agg

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501", "--browser.gatherUsageStats=false"]
